<script setup lang="ts">
import {ref,computed} from 'vue'
import {message} from 'ant-design-vue'
import * as XLSX from 'xlsx'
import type {SupplementField} from '@/api/supplement'
const props=defineProps<{fields:SupplementField[];title:string;disabled?:boolean}>()
const emit=defineEmits<{import:[rows:Record<string,any>[]]}>()
const open=ref(false),preview=ref<Record<string,any>[]>([]),errors=ref<string[]>([]),reading=ref(false)
const columns=computed(()=>props.fields.map(f=>({title:f.label,dataIndex:f.key,width:160})))
function template(){const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([props.fields.map(f=>f.label)]),'补录数据');XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([['字段','填写要求'],...props.fields.map(f=>[f.label,[f.required?'必填':'选填',f.type==='date'?'日期格式 YYYY-MM-DD':f.type==='number'?'非负数字':'',f.options?.map(o=>typeof o==='string'?o:o.label).join(' / ')||'',f.requiredWhen?`当 ${props.fields.find(i=>i.key===f.requiredWhen?.field)?.label||f.requiredWhen.field} 为 ${f.requiredWhen.value} 时必填`:''].filter(Boolean).join('；')])]),'填写说明');XLSX.writeFile(workbook,`${props.title}补录模板.xlsx`)}
async function read(event:Event){const target=event.target as HTMLInputElement,file=target.files?.[0];if(!file)return;reading.value=true;errors.value=[];preview.value=[];try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const sheet=workbook.Sheets['补录数据']||workbook.Sheets[workbook.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Record<string,any>>(sheet,{defval:'',raw:true});if(rows.length>1000)throw new Error('单次最多导入 1000 条记录，请拆分文件');const header=XLSX.utils.sheet_to_json<any[]>(sheet,{header:1})[0]||[];for(const f of props.fields)if(!header.includes(f.label))errors.value.push(`缺少列：${f.label}，请使用当前模板`);preview.value=rows.map((row,index)=>{const result:Record<string,any>={};for(const f of props.fields){let value=row[f.label]??'';if(value instanceof Date)value=[value.getFullYear(),String(value.getMonth()+1).padStart(2,'0'),String(value.getDate()).padStart(2,'0')].join('-');if(typeof value==='string')value=value.trim();result[f.key]=value}for(const f of props.fields){let value=result[f.key];const required=f.required||(f.requiredWhen&&result[f.requiredWhen.field]===f.requiredWhen.value)||(f.requiredWhenAll?.length&&f.requiredWhenAll.every(c=>result[c.field]===c.value));if(required&&value==='')errors.value.push(`第 ${index+2} 行：${f.label}未填写`);if(value!==''&&f.type==='number'){if(!Number.isFinite(Number(value))||Number(value)<0)errors.value.push(`第 ${index+2} 行：${f.label}必须是非负数字`);else result[f.key]=Number(value)}if(value!==''&&f.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value))))errors.value.push(`第 ${index+2} 行：${f.label}日期格式错误`);if(value!==''&&f.options){const option=f.options.find(o=>typeof o==='string'?o===value:o.value===value||o.label===value);if(!option)errors.value.push(`第 ${index+2} 行：${f.label}不在允许选项中`);else result[f.key]=typeof option==='string'?option:option.value}}return result});if(!preview.value.length)errors.value.push('文件没有数据行');open.value=true}catch(e:any){message.error(e.message||'无法解析文件，请使用模板填写')}finally{reading.value=false;target.value=''}}
function apply(){if(errors.value.length)return;emit('import',preview.value);open.value=false;message.success(`已追加 ${preview.value.length} 条记录，请核对并保存草稿`)}
</script>
<template><span class="import-actions"><a-button size="small" :disabled="disabled" @click="template">下载模板</a-button><label class="import-file" :class="{disabled:disabled||reading}"><input type="file" accept=".xlsx,.xls" :disabled="disabled||reading" @change="read" />{{reading?'解析中…':'导入 Excel'}}</label></span><a-modal v-model:open="open" title="导入预览 · 核对后追加至草稿" width="90%" :ok-button-props="{disabled:errors.length>0}" ok-text="确认追加" @ok="apply"><a-alert :type="errors.length?'error':'success'" :message="errors.length?`发现 ${errors.length} 处问题，请修改文件后重新导入`:`已解析 ${preview.length} 条记录，确认后追加，不覆盖现有记录`" show-icon /><ul v-if="errors.length" class="import-errors"><li v-for="(error,index) in errors" :key="index">{{error}}</li></ul><a-table size="small" :columns="columns" :data-source="preview" :row-key="(_,index)=>String(index)" :scroll="{x:columns.length*160,y:350}" :pagination="{pageSize:10}" /></a-modal></template>
<style scoped>.import-actions{display:inline-flex;gap:8px}.import-file{border:1px solid #d9d9d9;border-radius:4px;padding:0 7px;line-height:22px;cursor:pointer;font-size:14px}.import-file input{display:none}.disabled{opacity:.5;cursor:default}.import-errors{max-height:180px;overflow:auto;color:#bd4444}</style>

